### PR TITLE
Switch to Go modules

### PR DESCRIPTION
**Pull request by benweint**
This is an extension of the work in https://github.com/ricardo-ch/go-kafka-connect/pull/37 that attempts to address the feedback from @FrancoisPoinsot in [this comment](https://github.com/ricardo-ch/go-kafka-connect/pull/37#pullrequestreview-498216203).

Specifically:

- The module name is now `github.com/ricardo-ch/go-kafka-connect/v3` (the `v3` being because of the fact that the latest tagged version appears to be 2.1.0, and bumping the major version is recommended when switching to modules)
- Internal import paths have been updated accordingly

### CODE REVIEW

**Comment by FrancoisPoinsot** [comment]
I can't help anymore on this project
maybe @EtienneGuerlais can help?

**Comment by benweint** [comment]
Thanks for pointing me in the right direction, @FrancoisPoinsot!

**Review by EtienneGuerlais — APPROVED** [review]
Thank you @benweint for the contribution!

I have tested it locally and it works just fine, so I'd be glad to merge it.

I will give it a few days to give the opportunity to other devs to have a look then merge it and create the new release 🙂

**Comment by benweint** [comment]
Thanks so much @EtienneGuerlais!

**Pull request merged**
